intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
plat_libs = # Platform depencencies.

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glfw"))
  import intf_libs += glfw%lib{glfw}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl2"))
  fail "SDL2 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl3"))
  fail "SDL3 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "allegro5"))
  fail "Allegro5 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glut"))
  fail "GLUT backend unsupported in this package; consider contributing an implementation."

# Win32 backend requires platform graphics libraries.
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "win32"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ldwmapi -lgdi32
    else
      plat_libs += dwmapi.lib gdi32.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "osx"))
  fail "OSX backend unsupported; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "android"))
  fail "Android backend unsupported; consider contributing an implementation."

# OpenGL backends need libopengl-meta.
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl2"))
  import intf_libs += libopengl-meta%lib{opengl-gl}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl3"))
  import intf_libs += libopengl-meta%lib{opengl-gl}

# Vulkan backends
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "vulkan"))
{
  vulkan_libs =
  vulkan_poptions =
  vulkan_loptions =

  # Windows targets
  #
  if ($cxx.target.class == 'windows')
  {
    # MinGW-w64 (cross or native).
    #
    if ($cxx.target.system == 'mingw32')
    {
      # MinGW sysroot layout:
      #
      #   <sysroot>/mingw/include/
      #   <sysroot>/mingw/include/vulkan/
      #   <sysroot>/mingw/lib/
      #
      sysroot = $cxx.target.sys_root

      vulkan_poptions += "-I$sysroot/mingw/include"
      vulkan_poptions += "-I$sysroot/mingw/include/vulkan"
      vulkan_loptions += "-L$sysroot/mingw/lib"

      vulkan_libs     += -lvulkan-1
      vulkan_poptions += -DVK_PROTOTYPES
    }
    else
    {
      # MSVC / Windows SDK.
      #
      sdkr = $config.libimgui_docking.vulkan_sdk_root

      if ($sdkr != [null])
      {
        vulkan_poptions += "-I$sdkr/include/"

        libdir = ($cxx.target.cpu == 'x86_64'
                  ? "$sdkr/lib/"
                  : "$sdkr/lib32/")

        vulkan_loptions += "/LIBPATH:$libdir"
      }

      vulkan_libs     += vulkan-1.lib
      vulkan_poptions += -DVK_PROTOTYPES
    }
  }
  else
  {
    # POSIX targets (Linux, BSD, macOS).
    #
    sdkr = $config.libimgui_docking.vulkan_sdk_root

    if ($sdkr != [null])
    {
      vulkan_poptions += "-I$sdkr/include/"
      vulkan_loptions += "-L$sdkr/lib/"
    }

    vulkan_libs += -lvulkan
  }

  # Apply backend-specific loader and SDK flags to this build only.
  #
  plat_libs    += $vulkan_libs
  cxx.poptions += $vulkan_poptions
  cxx.loptions += $vulkan_loptions
}

# Direct3D backends.
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx9"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d9
    else
      plat_libs += d3d9.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx10"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d10 -ld3dcompiler
    else
      plat_libs += d3d10.lib d3dcompiler.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx11"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d11 -ld3dcompiler
    else
      plat_libs += d3d11.lib d3dcompiler.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx12"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d12 -ld3dcompiler -ldxgi
    else
      plat_libs += d3d12.lib d3dcompiler.lib dxgi.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "metal"))
  fail "Metal backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "wgpu"))
  fail "WebGPU backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer2"))
  fail "SDL Renderer 2 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer3"))
  fail "SDL Renderer 3 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlgpu3"))
  fail "SDL GPU 3 backend unsupported in this package; consider contributing an implementation."

# Backend source selection.
#
lib{imgui-docking}: {hxx cxx}{*}

lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_glfw}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glfw"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdl2}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl2"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdl3}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl3"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_allegro5}:        include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "allegro5"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_glut}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glut"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_win32}:           include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "win32"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_android}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "android"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_opengl2}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl2"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_opengl3}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl3"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_opengl3_loader}:  include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl3"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_vulkan}:          include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "vulkan"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx9}:             include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx9"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx10}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx10"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx11}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx11"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx12}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx12"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_metal}:           include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "metal"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_osx}:             include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "osx"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_wgpu}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "wgpu"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdlrenderer2}:    include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer2"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdlrenderer3}:    include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer3"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdlgpu3}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlgpu3"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_sdlgpu3_shaders}: include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlgpu3"))

# Note that ordering here matters. In particular, some backends (e.g., GLFW) expect
# their symbols to precede ImGui's own backend glue during resolution on Windows
# targets.
#
lib{imgui-docking}: $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base" "-I$out_base"
cxx.poptions =+ "-DIMGUI_EXPORT" "-DIMGUI_IMPL_EXPORT"

cxx.libs += $plat_libs

#obja{*}: cxx.poptions += -DLIBIMGUI_DOCKING_STATIC_BUILD
#objs{*}: cxx.poptions += -DLIBIMGUI_DOCKINGSHARED_BUILD

# Export options.
#
lib{imgui-docking}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base" "-I$out_base"
  cxx.export.libs = $intf_libs $plat_libs
}

liba{imgui-docking}: cxx.export.poptions += -DIMGUI_STATIC
#libs{imgui-docking}: cxx.export.poptions += -DLIBIMGUI_DOCKING_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{imgui-docking}: bin.lib.version = "-$version.project_id"
else
  lib{imgui-docking}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libimgui-docking/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libimgui-docking/
  install.subdirs = true
}
