intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
plat_libs = # Platform depencencies.

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glfw"))
  import intf_libs += glfw%lib{glfw}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl2"))
  fail "SDL2 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl3"))
  fail "SDL3 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "allegro5"))
  fail "Allegro5 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glut"))
  fail "GLUT backend unsupported in this package; consider contributing an implementation."

# Win32 backend requires platform graphics libraries.
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "win32"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ldwmapi -lgdi32
    else
      plat_libs += dwmapi.lib gdi32.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "osx"))
  fail "OSX backend unsupported; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "android"))
  fail "Android backend unsupported; consider contributing an implementation."

# OpenGL backends need libopengl-meta.
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl2"))
  import intf_libs += libopengl-meta%lib{opengl-gl}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl3"))
  import intf_libs += libopengl-meta%lib{opengl-gl}

# Vulkan backends
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "vulkan"))
{
  vulkan_libs =
  vulkan_poptions =
  vulkan_loptions =

  # Windows targets
  #
  if ($cxx.target.class == 'windows')
  {
    # MinGW-w64 (cross or native).
    #
    if ($cxx.target.system == 'mingw32')
    {
      # MinGW sysroot layout:
      #
      #   <sysroot>/mingw/include/
      #   <sysroot>/mingw/include/vulkan/
      #   <sysroot>/mingw/lib/
      #
      sysroot = $cxx.target.sys_root

      vulkan_poptions += "-I$sysroot/mingw/include"
      vulkan_poptions += "-I$sysroot/mingw/include/vulkan"
      vulkan_loptions += "-L$sysroot/mingw/lib"

      vulkan_libs     += -lvulkan-1
      vulkan_poptions += -DVK_PROTOTYPES
    }
    else
    {
      # MSVC / Windows SDK.
      #
      sdkr = $config.libimgui_docking.vulkan_sdk_root

      if ($sdkr != [null])
      {
        vulkan_poptions += "-I$sdkr/include/"

        libdir = ($cxx.target.cpu == 'x86_64'
                  ? "$sdkr/lib/"
                  : "$sdkr/lib32/")

        vulkan_loptions += "/LIBPATH:$libdir"
      }

      vulkan_libs     += vulkan-1.lib
      vulkan_poptions += -DVK_PROTOTYPES
    }
  }
  else
  {
    # POSIX targets (Linux, BSD, macOS).
    #
    sdkr = $config.libimgui_docking.vulkan_sdk_root

    if ($sdkr != [null])
    {
      vulkan_poptions += "-I$sdkr/include/"
      vulkan_loptions += "-L$sdkr/lib/"
    }

    vulkan_libs += -lvulkan
  }

  # Apply backend-specific loader and SDK flags to this build only.
  #
  plat_libs    += $vulkan_libs
  cxx.poptions += $vulkan_poptions
  cxx.loptions += $vulkan_loptions
}

# Direct3D backends.
#
if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx9"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d9
    else
      plat_libs += d3d9.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx10"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d10 -ld3dcompiler
    else
      plat_libs += d3d10.lib d3dcompiler.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx11"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d11 -ld3dcompiler
    else
      plat_libs += d3d11.lib d3dcompiler.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx12"))
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
      plat_libs += -ld3d12 -ld3dcompiler -ldxgi
    else
      plat_libs += d3d12.lib d3dcompiler.lib dxgi.lib
  }
}

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "metal"))
  fail "Metal backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "wgpu"))
  fail "WebGPU backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer2"))
  fail "SDL Renderer 2 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer3"))
  fail "SDL Renderer 3 backend unsupported in this package; consider contributing an implementation."

if ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlgpu3"))
  fail "SDL GPU 3 backend unsupported in this package; consider contributing an implementation."

# Backend source selection.
#
lib{imgui-docking}: {hxx cxx}{* -imconfig} hxx{imconfig}

# Generate imconfig.h from template
#
hxx{imconfig}: in{imconfig}
{
  # Map config variables to #define statements (empty string if false/null)
  #
  IMGUI_DISABLE_OBSOLETE_FUNCTIONS                = ($config.libimgui_docking.disable_obsolete_functions                ? '#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS'                                                 : '')
  IMGUI_DISABLE                                   = ($config.libimgui_docking.disable                                   ? '#define IMGUI_DISABLE'                                                                    : '')
  IMGUI_DISABLE_DEMO_WINDOWS                      = ($config.libimgui_docking.disable_demo_windows                      ? '#define IMGUI_DISABLE_DEMO_WINDOWS'                                                       : '')
  IMGUI_DISABLE_DEBUG_TOOLS                       = ($config.libimgui_docking.disable_debug_tools                       ? '#define IMGUI_DISABLE_DEBUG_TOOLS'                                                        : '')
  IMGUI_DISABLE_WIN32_DEFAULT_CLIPBOARD_FUNCTIONS = ($config.libimgui_docking.disable_win32_default_clipboard_functions ? '#define IMGUI_DISABLE_WIN32_DEFAULT_CLIPBOARD_FUNCTIONS'                                  : '')
  IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS        = ($config.libimgui_docking.enable_win32_default_ime_functions        ? '#define IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS'                                         : '')
  IMGUI_DISABLE_WIN32_DEFAULT_IME_FUNCTIONS       = ($config.libimgui_docking.disable_win32_default_ime_functions       ? '#define IMGUI_DISABLE_WIN32_DEFAULT_IME_FUNCTIONS'                                        : '')
  IMGUI_DISABLE_WIN32_FUNCTIONS                   = ($config.libimgui_docking.disable_win32_functions                   ? '#define IMGUI_DISABLE_WIN32_FUNCTIONS'                                                    : '')
  IMGUI_ENABLE_OSX_DEFAULT_CLIPBOARD_FUNCTIONS    = ($config.libimgui_docking.enable_osx_default_clipboard_functions    ? '#define IMGUI_ENABLE_OSX_DEFAULT_CLIPBOARD_FUNCTIONS'                                     : '')
  IMGUI_DISABLE_DEFAULT_SHELL_FUNCTIONS           = ($config.libimgui_docking.disable_default_shell_functions           ? '#define IMGUI_DISABLE_DEFAULT_SHELL_FUNCTIONS'                                            : '')
  IMGUI_DISABLE_DEFAULT_FORMAT_FUNCTIONS          = ($config.libimgui_docking.disable_default_format_functions          ? '#define IMGUI_DISABLE_DEFAULT_FORMAT_FUNCTIONS'                                           : '')
  IMGUI_DISABLE_DEFAULT_MATH_FUNCTIONS            = ($config.libimgui_docking.disable_default_math_functions            ? '#define IMGUI_DISABLE_DEFAULT_MATH_FUNCTIONS'                                             : '')
  IMGUI_DISABLE_FILE_FUNCTIONS                    = ($config.libimgui_docking.disable_file_functions                    ? '#define IMGUI_DISABLE_FILE_FUNCTIONS'                                                     : '')
  IMGUI_DISABLE_DEFAULT_FILE_FUNCTIONS            = ($config.libimgui_docking.disable_default_file_functions            ? '#define IMGUI_DISABLE_DEFAULT_FILE_FUNCTIONS'                                             : '')
  IMGUI_DISABLE_DEFAULT_ALLOCATORS                = ($config.libimgui_docking.disable_default_allocators                ? '#define IMGUI_DISABLE_DEFAULT_ALLOCATORS'                                                 : '')
  IMGUI_DISABLE_DEFAULT_FONT                      = ($config.libimgui_docking.disable_default_font                      ? '#define IMGUI_DISABLE_DEFAULT_FONT'                                                       : '')
  IMGUI_DISABLE_SSE                               = ($config.libimgui_docking.disable_sse                               ? '#define IMGUI_DISABLE_SSE'                                                                : '')
  IMGUI_ENABLE_TEST_ENGINE                        = ($config.libimgui_docking.enable_test_engine                        ? '#define IMGUI_ENABLE_TEST_ENGINE'                                                         : '')
  IMGUI_INCLUDE_IMGUI_USER_H                      = ($config.libimgui_docking.include_imgui_user_h                      ? '#define IMGUI_INCLUDE_IMGUI_USER_H'                                                       : '')
  IMGUI_USER_H_FILENAME                           = ($config.libimgui_docking.user_h_filename != [null]                 ? "#define IMGUI_USER_H_FILENAME \"$config.libimgui_docking.user_h_filename\""               : '')
  IMGUI_USE_BGRA_PACKED_COLOR                     = ($config.libimgui_docking.use_bgra_packed_color                     ? '#define IMGUI_USE_BGRA_PACKED_COLOR'                                                      : '')
  IMGUI_USE_LEGACY_CRC32_ADLER                    = ($config.libimgui_docking.use_legacy_crc32_adler                    ? '#define IMGUI_USE_LEGACY_CRC32_ADLER'                                                     : '')
  IMGUI_USE_WCHAR32                               = ($config.libimgui_docking.use_wchar32                               ? '#define IMGUI_USE_WCHAR32'                                                                : '')
  IMGUI_STB_TRUETYPE_FILENAME                     = ($config.libimgui_docking.stb_truetype_filename != [null]           ? "#define IMGUI_STB_TRUETYPE_FILENAME \"$config.libimgui_docking.stb_truetype_filename\""   : '')
  IMGUI_STB_RECT_PACK_FILENAME                    = ($config.libimgui_docking.stb_rect_pack_filename != [null]          ? "#define IMGUI_STB_RECT_PACK_FILENAME \"$config.libimgui_docking.stb_rect_pack_filename\"" : '')
  IMGUI_STB_SPRINTF_FILENAME                      = ($config.libimgui_docking.stb_sprintf_filename != [null]            ? "#define IMGUI_STB_SPRINTF_FILENAME \"$config.libimgui_docking.stb_sprintf_filename\""     : '')
  IMGUI_DISABLE_STB_TRUETYPE_IMPLEMENTATION       = ($config.libimgui_docking.disable_stb_truetype_implementation       ? '#define IMGUI_DISABLE_STB_TRUETYPE_IMPLEMENTATION'                                        : '')
  IMGUI_DISABLE_STB_RECT_PACK_IMPLEMENTATION      = ($config.libimgui_docking.disable_stb_rect_pack_implementation      ? '#define IMGUI_DISABLE_STB_RECT_PACK_IMPLEMENTATION'                                       : '')
  IMGUI_DISABLE_STB_SPRINTF_IMPLEMENTATION        = ($config.libimgui_docking.disable_stb_sprintf_implementation        ? '#define IMGUI_DISABLE_STB_SPRINTF_IMPLEMENTATION'                                         : '')
  IMGUI_USE_STB_SPRINTF                           = ($config.libimgui_docking.use_stb_sprintf                           ? '#define IMGUI_USE_STB_SPRINTF'                                                            : '')
  IMGUI_ENABLE_FREETYPE                           = ($config.libimgui_docking.enable_freetype                           ? '#define IMGUI_ENABLE_FREETYPE'                                                            : '')
  IMGUI_ENABLE_FREETYPE_PLUTOSVG                  = ($config.libimgui_docking.enable_freetype_plutosvg                  ? '#define IMGUI_ENABLE_FREETYPE_PLUTOSVG'                                                   : '')
  IMGUI_ENABLE_FREETYPE_LUNASVG                   = ($config.libimgui_docking.enable_freetype_lunasvg                   ? '#define IMGUI_ENABLE_FREETYPE_LUNASVG'                                                    : '')
  IMGUI_ENABLE_STB_TRUETYPE                       = ($config.libimgui_docking.enable_stb_truetype                       ? '#define IMGUI_ENABLE_STB_TRUETYPE'                                                        : '')
  IMGUI_DEFINE_MATH_OPERATORS                     = ($config.libimgui_docking.define_math_operators                     ? '#define IMGUI_DEFINE_MATH_OPERATORS'                                                      : '')
  IMGUI_DEBUG_HIGHLIGHT_ALL_ID_CONFLICTS          = ($config.libimgui_docking.debug_highlight_all_id_conflicts          ? '#define IMGUI_DEBUG_HIGHLIGHT_ALL_ID_CONFLICTS'                                           : '')
  IMGUI_DEBUG_PARANOID                            = ($config.libimgui_docking.debug_paranoid                            ? '#define IMGUI_DEBUG_PARANOID'                                                             : '')
}

hxx{imconfig}:
{
  # Include the generated config into the distribution and don't it when
  # cleaning in src (so that clean results in a state identical to distributed).
  #
  dist  = true
  clean = ($src_root != $out_root)

  # We keep the generated code in the repository so copy it back to src in case
  # of a forwarded configuration.
  #
  backlink = overwrite
}

lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_glfw}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glfw"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdl2}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl2"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdl3}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdl3"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_allegro5}:        include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "allegro5"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_glut}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "glut"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_win32}:           include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "win32"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_android}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "android"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_opengl2}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl2"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_opengl3}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl3"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_opengl3_loader}:  include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "opengl3"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_vulkan}:          include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "vulkan"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx9}:             include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx9"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx10}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx10"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx11}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx11"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_dx12}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "dx12"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_metal}:           include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "metal"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_osx}:             include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "osx"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_wgpu}:            include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "wgpu"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdlrenderer2}:    include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer2"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdlrenderer3}:    include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlrenderer3"))
lib{imgui-docking}: {hxx cxx}{backends/imgui_impl_sdlgpu3}:         include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlgpu3"))
lib{imgui-docking}: {hxx    }{backends/imgui_impl_sdlgpu3_shaders}: include = ($config.libimgui_docking.backend != [null] && $find($config.libimgui_docking.backend, "sdlgpu3"))

# Note that ordering here matters. In particular, some backends (e.g., GLFW) expect
# their symbols to precede ImGui's own backend glue during resolution on Windows
# targets.
#
lib{imgui-docking}: $impl_libs $intf_libs

# Build options.
#

cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base" "-I$out_base"
cxx.poptions =+ "-DIMGUI_EXPORT" "-DIMGUI_IMPL_EXPORT"

cxx.libs += $plat_libs

#obja{*}: cxx.poptions += -DLIBIMGUI_DOCKING_STATIC_BUILD
#objs{*}: cxx.poptions += -DLIBIMGUI_DOCKINGSHARED_BUILD

# Export options.
#
lib{imgui-docking}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base" "-I$out_base"
  cxx.export.libs = $intf_libs $plat_libs
}

liba{imgui-docking}: cxx.export.poptions += -DIMGUI_STATIC
#libs{imgui-docking}: cxx.export.poptions += -DLIBIMGUI_DOCKING_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{imgui-docking}: bin.lib.version = "-$version.project_id"
else
  lib{imgui-docking}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libimgui-docking/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libimgui-docking/
  install.subdirs = true
}
